"use client";
import { useState, useRef } from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import Navbar from "@/components/Navbar"; import Footer from "@/components/Footer"; import ScrollToTop from "@/components/ScrollToTop"; import HeaderBackgroundSlider from "@/components/HeaderBackgroundSlider";
import Link from "next/link";
import { CheckCircle2, ArrowRight, ArrowLeft, ChevronRight, Mail, Phone, User, Loader2, RefreshCw, Navigation, Shield } from "lucide-react";
const BG=[{url:"https://images.unsplash.com/photo-1530521954074-e64f6810b32d?auto=format&fit=crop&q=80&w=1200",type:"image"as const,theme:"dark"as const},{url:"https://images.unsplash.com/photo-1548345680-f5475ea5df84?auto=format&fit=crop&q=80&w=1200",type:"image"as const,theme:"dark"as const}];
const BRANDS=[
  {id:"garmin",label:"Garmin",icon:"🟠",tool:"Garmin Express",steps:["Download Garmin Express from garmin.com/express on your computer","Connect your Garmin GPS to your computer using the USB cable that came with it","Open Garmin Express — it will automatically detect your device","Click 'Add a Device' if it's your first time, or wait for it to check for updates","Click 'Install All' to download and install the latest maps","Keep your GPS connected until the installation is fully complete (can take 30-60 mins)","Safely disconnect your GPS and enjoy your updated maps!"],tip:"Garmin maps update quarterly. You can get one free map update per year on most devices, or buy a Lifetime Maps subscription for unlimited updates."},
  {id:"tomtom",label:"TomTom",icon:"🔴",tool:"MyDrive Connect",steps:["Download MyDrive Connect from tomtom.com/mydrive-connect on your computer","Connect your TomTom GPS to your computer using the USB cable","Open MyDrive Connect — it will find your device automatically","Sign in to your TomTom account (or create a free one)","Click 'Update Now' when you see map updates are available","Wait for the download and installation to complete — keep device connected","Disconnect your TomTom and you're ready to go!"],tip:"TomTom releases map updates regularly. If you have a TomTom HOME plan, updates are included. Otherwise, map updates can be purchased individually."},
  {id:"incar",label:"In-Car GPS",icon:"🚗",tool:"your car manufacturer's app",steps:["Check your car's owner manual for the GPS system brand (common ones: Honda Navigation, Toyota Navigation, Ford SYNC)","Visit your car manufacturer's website and search for 'map update' or 'navigation update'","Download the manufacturer's map update app or USB update tool for your car model","Follow the on-screen instructions — most in-car GPS updates require a USB drive","Download the map files to the USB drive, then insert it into your car's USB port","Start your car and follow the on-screen prompts to install the update","The installation may take 20-45 minutes — keep the car running during this time"],tip:"In-car GPS map updates can be more expensive than standalone GPS units. Check if your car's navigation subscription includes free updates — many newer cars offer 3-5 years of free updates."},
  {id:"magellan",label:"Magellan",icon:"🔵",tool:"Magellan Content Manager",steps:["Download Magellan Content Manager from magellan.com on your computer","Connect your Magellan GPS via USB cable to your computer","Open Magellan Content Manager and sign in to your account","The software will check for available map updates automatically","Select the map update you want to download and install","Keep your GPS connected throughout the entire update process","Once complete, disconnect and you're ready to navigate!"],tip:"Magellan offers both free and paid map updates depending on your device model and when you purchased it. Check your device's documentation for update eligibility."},
];
export default function GPSUpdateClient(){
  const [stage,setStage]=useState<"intro"|"brand"|"steps"|"lead"|"done">("intro");
  const [brand,setBrand]=useState<typeof BRANDS[0]|null>(null);
  const [completedSteps,setCompletedSteps]=useState<number[]>([]);
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState("");
  const [errors,setErrors]=useState<Record<string,string>>({}); const [submitting,setSubmitting]=useState(false); const [submitted,setSubmitted]=useState(false);
  const heroRef=useRef(null); const heroInView=useInView(heroRef,{once:true});
  const allDone=brand&&completedSteps.length===brand.steps.length;
  const toggleStep=(i:number)=>setCompletedSteps(p=>p.includes(i)?p.filter(x=>x!==i):[...p,i]);
  const validate=()=>{const e:Record<string,string>={};if(!name.trim())e.name="Please enter your name";if(!email.trim()||!email.includes("@"))e.email="Please enter a valid email";setErrors(e);return Object.keys(e).length===0;};
  const handleSubmit=async()=>{if(!validate())return;setSubmitting(true);try{await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,phone,brand:brand?.label,issue:`GPS Update Guide — ${brand?.label}`,source:"gps-update-guide"})});}catch{}setSubmitted(true);setSubmitting(false);setStage("done");};
  const reset=()=>{setStage("intro");setBrand(null);setCompletedSteps([]);setName("");setEmail("");setPhone("");setSubmitted(false);};
  return(
    <div className="min-h-screen bg-[#0d1117] text-white font-sans"><Navbar/><ScrollToTop/>
      <header ref={heroRef} className="relative pt-44 pb-32 overflow-hidden">
        <HeaderBackgroundSlider items={BG} interval={8000}/>
        <div className="absolute inset-0 -z-10"/>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <nav className="flex items-center gap-2 text-base text-zinc-400 mb-8"><Link href="/" className="hover:text-white">Home</Link><ChevronRight size={16}/><Link href="/tools" className="hover:text-white">Free Tools</Link><ChevronRight size={16}/><span className="text-zinc-200">GPS Update Guide</span></nav>
          <motion.div initial={{opacity:0,x:-20}} animate={heroInView?{opacity:1,x:0}:{}} transition={{delay:0.2}} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-sm font-black uppercase tracking-widest mb-8"><Navigation size={14}/>Free Guide · Step-by-Step</motion.div>
          <h1 className="text-5xl md:text-7xl font-black leading-none tracking-tighter mb-6 text-white max-w-3xl">
            <motion.span className="block" initial={{opacity:0,filter:"blur(8px)"}} animate={heroInView?{opacity:1,filter:"blur(0px)"}:{}} transition={{delay:0.3,duration:0.8}}>How to Update</motion.span>
            <motion.span className="block bg-gradient-to-r from-emerald-400 to-teal-300 bg-clip-text text-transparent italic" initial={{opacity:0,filter:"blur(8px)"}} animate={heroInView?{opacity:1,filter:"blur(0px)"}:{}} transition={{delay:0.45,duration:0.8}}>Your GPS Maps</motion.span>
          </h1>
          <motion.p initial={{opacity:0}} animate={heroInView?{opacity:1}:{}} transition={{delay:0.6}} className="text-xl md:text-2xl text-zinc-300 font-medium max-w-2xl mb-8 leading-relaxed">Plain-English step-by-step guide for Garmin, TomTom, Magellan, and in-car GPS systems. Select your device and follow along — no technical knowledge needed.</motion.p>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#0d1117] to-transparent"/>
      </header>
      <section className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-28">
        <AnimatePresence mode="wait">
          {stage==="intro"&&(<motion.div key="intro" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-emerald-500 to-teal-400"/><div className="p-8 md:p-10"><h2 className="text-3xl font-black text-white mb-4">Which GPS Do You Have? 🧭</h2><p className="text-zinc-400 font-medium mb-8 text-lg leading-relaxed">Select your GPS brand below and we'll walk you through the exact steps to update your maps — in plain English, with no confusing technical terms.</p><div className="grid grid-cols-2 gap-4 mb-8">{BRANDS.map(b=>(<button key={b.id} onClick={()=>{setBrand(b);setStage("steps");}} className="flex flex-col items-center gap-3 p-6 bg-zinc-800 rounded-2xl border-2 border-zinc-700 hover:border-emerald-500 hover:bg-emerald-900/20 transition-all group"><span className="text-4xl">{b.icon}</span><span className="font-black text-white text-lg group-hover:text-emerald-300 transition-colors">{b.label}</span><span className="text-zinc-500 text-sm text-center">Updates via {b.tool}</span></button>))}</div><div className="p-5 bg-blue-900/20 border border-blue-800 rounded-2xl"><div className="flex items-start gap-3"><Shield size={16} className="text-blue-400 mt-0.5 shrink-0"/><p className="text-sm text-blue-300 font-medium">Educational guide only. Setwise Digital is not affiliated with Garmin, TomTom, Magellan, or any GPS manufacturer.</p></div></div></div></motion.div>)}
          {stage==="steps"&&brand&&(<motion.div key="steps" initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-40}} className="space-y-6">
            <div className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-emerald-500 to-teal-400"/><div className="p-8 md:p-10">
              <button onClick={()=>setStage("intro")} className="flex items-center gap-2 text-zinc-400 hover:text-white text-base font-bold mb-6"><ArrowLeft size={18}/>Back</button>
              <div className="flex items-center gap-4 mb-6"><span className="text-4xl">{brand.icon}</span><div><h2 className="text-3xl font-black text-white">How to Update {brand.label} Maps</h2><p className="text-zinc-400 text-base mt-1">Using {brand.tool}</p></div></div>
              <div className="bg-amber-900/20 border border-amber-700 rounded-2xl p-5 mb-8"><p className="text-base text-amber-300 font-medium">💡 <strong>Tip:</strong> {brand.tip}</p></div>
              <p className="text-zinc-400 font-medium mb-6 text-lg">Check off each step as you complete it:</p>
              <div className="space-y-4">
                {brand.steps.map((step,i)=>(<motion.button key={i} whileTap={{scale:0.99}} onClick={()=>toggleStep(i)} className={`w-full flex items-start gap-4 p-5 rounded-2xl border-2 text-left transition-all ${completedSteps.includes(i)?"border-emerald-500 bg-emerald-900/20":"border-zinc-700 bg-zinc-800/50 hover:border-zinc-500"}`}>
                  <div className={`w-8 h-8 rounded-full border-2 flex items-center justify-center shrink-0 mt-0.5 transition-all ${completedSteps.includes(i)?"border-emerald-500 bg-emerald-500":"border-zinc-600"}`}>{completedSteps.includes(i)?<CheckCircle2 size={16} className="text-white"/>:<span className="text-zinc-400 text-sm font-black">{i+1}</span>}</div>
                  <span className={`text-base font-medium leading-relaxed ${completedSteps.includes(i)?"text-emerald-300 line-through":"text-zinc-300"}`}>{step}</span>
                </motion.button>))}
              </div>
              {allDone&&(<motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mt-8"><div className="bg-emerald-900/30 border border-emerald-700 rounded-2xl p-6 text-center mb-6"><div className="text-4xl mb-3">🎉</div><h3 className="text-2xl font-black text-emerald-300 mb-2">All steps complete!</h3><p className="text-zinc-400">Your {brand.label} GPS maps are now updated. Enjoy accurate, current directions!</p></div><button onClick={()=>setStage("lead")} className="w-full py-6 bg-gradient-to-r from-emerald-600 to-teal-500 text-white font-black text-xl rounded-2xl flex items-center justify-center gap-3 shadow-xl shadow-emerald-500/25 hover:scale-[1.02] transition-transform">Get Your Printable Guide <ArrowRight size={24}/></button></motion.div>)}
              {!allDone&&<div className="mt-6 text-center text-zinc-500 text-base font-medium">{completedSteps.length} of {brand.steps.length} steps completed</div>}
            </div></div>
          </motion.div>)}
          {stage==="lead"&&(<motion.div key="lead" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-emerald-500 to-teal-400"/><div className="p-8 md:p-10"><div className="text-center mb-8"><div className="text-6xl mb-4">📋</div><h2 className="text-3xl font-black text-white mb-3">Get Your Printable Guide!</h2><p className="text-zinc-400 font-medium text-lg">Enter your email and we'll send you a printable version of this guide plus monthly GPS tips for drivers 45+.</p></div><div className="space-y-4 mb-6">{[{label:"First Name *",type:"text",val:name,set:setName,ph:"e.g. Mary",key:"name"},{label:"Email Address *",type:"email",val:email,set:setEmail,ph:"name@email.com",key:"email"},{label:"Phone (optional)",type:"tel",val:phone,set:setPhone,ph:"+1 555 000 0000",key:"phone"}].map(f=>(<div key={f.key}><label className="text-sm font-black text-zinc-400 uppercase tracking-widest block mb-2">{f.label}</label><input type={f.type} value={f.val} onChange={e=>f.set(e.target.value)} placeholder={f.ph} className="w-full px-4 py-4 bg-zinc-800 border border-zinc-700 rounded-xl text-white focus:outline-none focus:border-emerald-500 transition-colors placeholder:text-zinc-600 text-lg font-medium"/>{errors[f.key]&&<p className="text-red-400 text-sm mt-1 font-bold">{errors[f.key]}</p>}</div>))}</div><button onClick={handleSubmit} disabled={submitting} className="w-full py-6 bg-gradient-to-r from-emerald-600 to-teal-500 text-white font-black text-xl rounded-2xl flex items-center justify-center gap-3 mb-4 hover:scale-[1.02] transition-transform disabled:opacity-70">{submitting?<Loader2 size={24} className="animate-spin"/>:<>Send My Guide</>}</button><button onClick={()=>setStage("done")} className="w-full text-center text-base text-zinc-500 hover:text-zinc-300 font-medium py-2">Skip</button></div></motion.div>)}
          {stage==="done"&&(<motion.div key="done" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-emerald-500 to-teal-400"/><div className="p-8 md:p-10 text-center"><div className="text-6xl mb-6">✅</div><h2 className="text-3xl font-black text-white mb-3">Your GPS Maps Are Updated!</h2>{submitted&&<p className="text-emerald-300 font-medium mb-6">Guide sent to {email} — check your inbox.</p>}<p className="text-zinc-400 font-medium text-lg mb-8">Your {brand?.label} GPS now has the latest maps. You're ready for accurate directions on your next trip!</p><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><button onClick={reset} className="flex items-center justify-center gap-2 py-5 border-2 border-zinc-700 rounded-2xl font-black text-zinc-300 hover:border-zinc-500 text-lg"><RefreshCw size={20}/>Update Another GPS</button><Link href="/tools/road-trip-checker"><div className="flex items-center justify-center gap-2 py-5 bg-gradient-to-r from-green-600 to-emerald-500 text-white font-black rounded-2xl text-lg cursor-pointer hover:scale-[1.02] transition-transform"><Navigation size={20}/>Road Trip Checklist</div></Link></div></div></motion.div>)}
        </AnimatePresence>
      </section>
      <Footer/>
    </div>
  );
}
