"use client";
import { useState, useRef } from "react";
import { motion, AnimatePresence, useInView } from "framer-motion";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ScrollToTop from "@/components/ScrollToTop";
import HeaderBackgroundSlider from "@/components/HeaderBackgroundSlider";
import Link from "next/link";
import { CheckCircle2, ArrowRight, ArrowLeft, ChevronRight, Mail, Phone, User, Loader2, Navigation, Shield, RefreshCw, Award, Star } from "lucide-react";

const BG = [
  { url:"https://images.unsplash.com/photo-1548345680-f5475ea5df84?auto=format&fit=crop&q=60&w=1200", type:"image" as const, theme:"dark" as const },
  { url:"https://images.unsplash.com/photo-1494783367193-149034c05e8f?auto=format&fit=crop&q=60&w=1200", type:"image" as const, theme:"dark" as const },
  { url:"https://images.unsplash.com/photo-1530521954074-e64f6810b32d?auto=format&fit=crop&q=60&w=1200", type:"image" as const, theme:"dark" as const },
];
const GPS = [
  { id:"g52", name:"Garmin Drive 52", brand:"Garmin", price:"$89–$109", pMin:89, screen:"5-inch", bestFor:["Beginners","Budget-conscious"], features:["Turn-by-turn voice","Speed limit alerts","Simple menu","Bright screen"], pros:["Very affordable","Simple to use","Reliable Garmin quality"], cons:["No live traffic","No Bluetooth"], badge:"Best for Beginners", badgeColor:"bg-green-600", emoji:"🟢", drivingType:["city","suburban","highway"], techLevel:"beginner", priority:["simple"] },
  { id:"g55", name:"Garmin DriveSmart 55", brand:"Garmin", price:"$149–$179", pMin:149, screen:"5.5-inch", bestFor:["Most drivers","Highway travel"], features:["Live traffic & weather","Bluetooth calls","Voice control","Wi-Fi map updates"], pros:["Best all-around","Live traffic","Hands-free calling"], cons:["Needs phone for live features"], badge:"Most Popular", badgeColor:"bg-blue-600", emoji:"⭐", drivingType:["city","suburban","highway","rural"], techLevel:"beginner", priority:["traffic","voice","simple"] },
  { id:"g65", name:"Garmin DriveSmart 65", brand:"Garmin", price:"$179–$219", pMin:179, screen:"6.95-inch", bestFor:["Seniors 65+","Large screen lovers"], features:["Extra-large 7\" screen","Live traffic","Bluetooth","Large text & buttons"], pros:["Biggest clearest screen","Easy to read driving","Voice control"], cons:["Larger size","Higher price"], badge:"Best Large Screen", badgeColor:"bg-purple-600", emoji:"👁️", drivingType:["city","suburban","highway"], techLevel:"beginner", priority:["simple","voice"] },
  { id:"tt520", name:"TomTom GO 520", brand:"TomTom", price:"$129–$159", pMin:129, screen:"5-inch", bestFor:["Independent travelers","No-phone users"], features:["Built-in Wi-Fi updates","World maps included","Offline navigation","Speed camera alerts"], pros:["Works without smartphone","World maps included","Easy Wi-Fi updates"], cons:["Older interface","Fewer live features"], badge:"Best Offline", badgeColor:"bg-red-600", emoji:"🔴", drivingType:["city","highway","rural"], techLevel:"beginner", priority:["offline"] },
  { id:"dezl", name:"Garmin dēzl OTR610", brand:"Garmin", price:"$249–$299", pMin:249, screen:"6-inch", bestFor:["RV drivers","Towing a trailer"], features:["RV & trailer routing","Campground finder","Custom vehicle profiles","Live traffic"], pros:["Avoids low bridges","Perfect for RV travel","Campground database"], cons:["Expensive","Overkill for city driving"], badge:"Best for RV", badgeColor:"bg-amber-600", emoji:"🚐", drivingType:["highway","rural"], techLevel:"intermediate", priority:["offline"] },
  { id:"g55t", name:"Garmin DriveSmart 55 + Traffic", brand:"Garmin", price:"$169–$199", pMin:169, screen:"5.5-inch", bestFor:["Commuters","City drivers"], features:["Real-time traffic","Incident alerts","Alternate routes","Bluetooth"], pros:["Saves time routing","Real-time alerts","Hands-free calling"], cons:["Needs smartphone"], badge:"Best for Traffic", badgeColor:"bg-cyan-600", emoji:"🚦", drivingType:["city","suburban","highway"], techLevel:"beginner", priority:["traffic"] },
];
const QS = [
  { id:"driving", title:"Where do you mostly drive?", subtitle:"Choose the one that fits your typical trips", options:[{value:"city",label:"City & suburbs",icon:"🏙️",desc:"Lots of traffic, frequent stops"},{value:"highway",label:"Highways & long trips",icon:"🛣️",desc:"Mostly straight routes, road trips"},{value:"rural",label:"Rural & back roads",icon:"🌲",desc:"Less-traveled routes, countryside"},{value:"rv",label:"RV or towing a trailer",icon:"🚐",desc:"Large vehicle, campsite routes"}]},
  { id:"budget", title:"What's your budget?", subtitle:"All options are quality devices", options:[{value:"low",label:"Under $100",icon:"💵",desc:"Best value basics"},{value:"mid",label:"$100 – $180",icon:"💳",desc:"Most popular range"},{value:"high",label:"$180 – $300",icon:"💎",desc:"Premium features"},{value:"any",label:"Best is fine",icon:"⭐",desc:"Just recommend the best"}]},
  { id:"screen", title:"How important is screen size?", subtitle:"Bigger screens are much easier to read while driving", options:[{value:"standard",label:"Standard size is fine",icon:"📱",desc:"5-inch screen"},{value:"large",label:"I want a big screen",icon:"📺",desc:"6-7 inch — easier to read"},{value:"any",label:"No preference",icon:"🤷",desc:"Whatever works best"}]},
  { id:"tech", title:"How comfortable are you with technology?", subtitle:"This helps us match the right complexity", options:[{value:"beginner",label:"I keep it simple",icon:"😊",desc:"Easy menus, big buttons"},{value:"intermediate",label:"I manage okay",icon:"👍",desc:"Can follow instructions"},{value:"advanced",label:"I love features",icon:"🚀",desc:"More options the better"}]},
  { id:"priority", title:"What matters most to you?", subtitle:"Your top priority shapes our recommendation", options:[{value:"traffic",label:"Avoiding traffic jams",icon:"🚦",desc:"Live traffic alerts"},{value:"offline",label:"Works without my phone",icon:"📵",desc:"No data needed"},{value:"voice",label:"Hands-free calling",icon:"📞",desc:"Bluetooth calls while driving"},{value:"simple",label:"Just easy to use",icon:"✨",desc:"Simple, reliable, no fuss"}]},
];
function score(d:typeof GPS[0], a:Record<string,string>){
  let s=0;
  if(d.drivingType.includes(a.driving))s+=30;
  if(a.budget==="low"&&d.pMin<=100)s+=25;else if(a.budget==="mid"&&d.pMin>=100&&d.pMin<=180)s+=25;else if(a.budget==="high"&&d.pMin>=180)s+=25;else if(a.budget==="any")s+=20;
  if(a.tech==="beginner"&&d.techLevel==="beginner")s+=20;else if(a.tech==="intermediate")s+=15;
  if(d.priority.includes(a.priority))s+=20;
  if(a.screen==="large"&&(d.screen.includes("6")||d.screen.includes("7")))s+=5;
  return Math.min(s,100);
}
export default function BestGPSFinderClient(){
  const [stage,setStage]=useState<"intro"|"quiz"|"lead"|"results">("intro");
  const [curQ,setCurQ]=useState(0); const [answers,setAnswers]=useState<Record<string,string>>({}); const [sel,setSel]=useState<string|null>(null);
  const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [phone,setPhone]=useState("");
  const [errors,setErrors]=useState<Record<string,string>>({}); const [submitting,setSubmitting]=useState(false); const [submitted,setSubmitted]=useState(false);
  const [currentTheme,setCurrentTheme]=useState<"dark"|"light">("dark");
  const heroRef=useRef(null); const heroInView=useInView(heroRef,{once:true});
  const ranked=GPS.map(d=>({...d,score:score(d,answers)})).sort((a,b)=>b.score-a.score);
  const top=ranked[0]; const progress=(curQ/QS.length)*100;
  const validate=()=>{const e:Record<string,string>={};if(!name.trim())e.name="Please enter your name";if(!email.trim()||!email.includes("@"))e.email="Please enter a valid email";setErrors(e);return Object.keys(e).length===0;};
  const answerQ=(v:string)=>{setSel(v);setTimeout(()=>{const na={...answers,[QS[curQ].id]:v};setAnswers(na);setSel(null);if(curQ<QS.length-1)setCurQ(p=>p+1);else setStage("lead");},280);};
  const handleSubmit=async()=>{if(!validate())return;setSubmitting(true);try{await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,email,phone,brand:top?.brand,issue:`GPS Finder — Top: ${top?.name}`,source:"best-gps-finder",extra:JSON.stringify(answers)})});}catch{}setSubmitted(true);setSubmitting(false);setStage("results");};
  const reset=()=>{setStage("intro");setCurQ(0);setAnswers({});setSel(null);setName("");setEmail("");setPhone("");setSubmitted(false);};
  return(
    <div className="min-h-screen bg-[#0d1117] text-white font-sans"><Navbar/><ScrollToTop/>
      <header ref={heroRef} className="relative pt-44 pb-32 overflow-hidden">
        <HeaderBackgroundSlider items={BG} interval={8000} onThemeChange={setCurrentTheme}/>
        <div className="absolute inset-0 -z-10"/>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <nav className="flex items-center gap-2 text-base text-zinc-400 mb-8"><Link href="/" className="hover:text-white">Home</Link><ChevronRight size={16}/><Link href="/tools" className="hover:text-white">Free Tools</Link><ChevronRight size={16}/><span className="text-zinc-200">Best GPS Finder</span></nav>
          <motion.div initial={{opacity:0,x:-20}} animate={heroInView?{opacity:1,x:0}:{}} transition={{delay:0.2}} className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full bg-blue-500/10 border border-blue-500/30 text-blue-300 text-sm font-black uppercase tracking-widest mb-8"><Navigation size={14}/>Free Tool · 4 Minutes</motion.div>
          <h1 className="text-5xl md:text-7xl font-black leading-none tracking-tighter mb-6 text-white max-w-3xl">
            <motion.span className="block" initial={{opacity:0,filter:"blur(8px)"}} animate={heroInView?{opacity:1,filter:"blur(0px)"}:{}} transition={{delay:0.3,duration:0.8}}>Best GPS Finder</motion.span>
            <motion.span className="block bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent italic" initial={{opacity:0,filter:"blur(8px)"}} animate={heroInView?{opacity:1,filter:"blur(0px)"}:{}} transition={{delay:0.45,duration:0.8}}>for You</motion.span>
          </h1>
          <motion.p initial={{opacity:0}} animate={heroInView?{opacity:1}:{}} transition={{delay:0.6}} className="text-xl md:text-2xl text-zinc-300 font-medium max-w-2xl mb-8 leading-relaxed">Not sure which GPS to buy? Answer 5 simple questions about your driving habits and budget. Get a personalized recommendation — in plain English, no jargon.</motion.p>
        </div>
        <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#0d1117] to-transparent"/>
      </header>
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 pb-28">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2">
            <AnimatePresence mode="wait">
              {stage==="intro"&&(<motion.div key="intro" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-blue-500 to-indigo-400"/><div className="p-8 md:p-10"><h2 className="text-3xl font-black text-white mb-4">Find Your Perfect GPS Match 🎯</h2><p className="text-zinc-400 font-medium mb-8 leading-relaxed text-lg">We'll ask 5 quick questions about how you drive, your budget, and what matters most. Then we'll match you to the best GPS — no complicated specs.</p><div className="space-y-3 mb-8">{QS.map((q,i)=>(<div key={q.id} className="flex items-center gap-4 p-5 bg-zinc-800/50 rounded-2xl border border-zinc-700/50"><div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-full flex items-center justify-center text-white font-black shrink-0">{i+1}</div><div className="font-black text-white text-base">{q.title}</div></div>))}</div><button onClick={()=>setStage("quiz")} className="w-full py-6 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-black text-xl rounded-2xl flex items-center justify-center gap-3 shadow-xl shadow-blue-500/25 hover:scale-[1.02] transition-transform">Find My Perfect GPS <ArrowRight size={24}/></button><p className="text-center text-base text-zinc-500 mt-4">🔒 No sign-up required to start</p></div></motion.div>)}
              {stage==="quiz"&&(<motion.div key={`q${curQ}`} initial={{opacity:0,x:40}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-40}} transition={{type:"spring",stiffness:400,damping:35}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-zinc-800 relative"><motion.div className="h-full bg-gradient-to-r from-blue-500 to-indigo-400 rounded-full" animate={{width:`${progress}%`}} transition={{duration:0.4}}/></div><div className="p-8 md:p-10"><div className="flex items-center justify-between mb-8"><button onClick={()=>{if(curQ===0)setStage("intro");else setCurQ(p=>p-1);}} className="flex items-center gap-2 text-zinc-400 hover:text-white text-base font-bold"><ArrowLeft size={18}/>Back</button><span className="text-base font-black text-zinc-400">Question {curQ+1} of {QS.length}</span></div>{(()=>{const q=QS[curQ];return(<div className="space-y-6"><div><div className="flex items-center gap-3 mb-3"><div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-500 rounded-xl flex items-center justify-center text-white font-black">{curQ+1}</div></div><h3 className="text-2xl md:text-3xl font-black text-white mb-2">{q.title}</h3><p className="text-zinc-400 text-base">{q.subtitle}</p></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{q.options.map(opt=>(<motion.button key={opt.value} whileTap={{scale:0.97}} onClick={()=>answerQ(opt.value)} className={`p-6 rounded-2xl border-2 text-left transition-all ${sel===opt.value||answers[q.id]===opt.value?"border-blue-500 bg-blue-900/30 shadow-lg":"border-zinc-700 bg-zinc-800/50 hover:border-zinc-500"}`}><div className="text-3xl mb-3">{opt.icon}</div><div className="font-black text-white text-base mb-1">{opt.label}</div><div className="text-zinc-400 text-sm">{opt.desc}</div>{(sel===opt.value||answers[q.id]===opt.value)&&<motion.div initial={{scale:0}} animate={{scale:1}} className="mt-3"><CheckCircle2 size={18} className="text-blue-400"/></motion.div>}</motion.button>))}</div></div>);})()}</div></motion.div>)}
              {stage==="lead"&&(<motion.div key="lead" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} exit={{opacity:0}} className="bg-zinc-900 rounded-[2rem] border border-zinc-800 overflow-hidden"><div className="h-1.5 bg-gradient-to-r from-blue-500 to-indigo-400"/><div className="p-8 md:p-10"><div className="text-center mb-8"><div className="text-6xl mb-4">🎯</div><h2 className="text-3xl font-black text-white mb-3">We found your perfect GPS match!</h2><p className="text-zinc-400 font-medium text-lg">Enter your email to receive your personalized recommendation report — device details, where to buy, and setup tips.</p></div><div className="bg-zinc-800 border border-zinc-700 rounded-2xl p-6 mb-6 space-y-3">{["🏆 Your #1 GPS recommendation with full details","💰 Price comparison across major retailers","📖 Plain-English setup guide for your device","💡 Monthly tips for drivers 45+"].map(item=>(<div key={item} className="flex items-center gap-3 text-base"><CheckCircle2 size={16} className="text-green-400 shrink-0"/><span className="text-zinc-300 font-medium">{item}</span></div>))}</div><div className="space-y-4 mb-6">{[{label:"First Name *",type:"text",val:name,set:setName,ph:"e.g. Mary",key:"name"},{label:"Email Address *",type:"email",val:email,set:setEmail,ph:"name@email.com",key:"email"},{label:"Phone (optional)",type:"tel",val:phone,set:setPhone,ph:"+1 555 000 0000",key:"phone"}].map(f=>(<div key={f.key}><label className="text-sm font-black text-zinc-400 uppercase tracking-widest block mb-2">{f.label}</label><input type={f.type} value={f.val} onChange={e=>f.set(e.target.value)} placeholder={f.ph} className="w-full px-4 py-4 bg-zinc-800 border border-zinc-700 rounded-xl text-white focus:outline-none focus:border-blue-500 transition-colors placeholder:text-zinc-600 text-lg font-medium"/>{errors[f.key]&&<p className="text-red-400 text-sm mt-1 font-bold">{errors[f.key]}</p>}</div>))}</div><button onClick={handleSubmit} disabled={submitting} className="w-full py-6 bg-gradient-to-r from-blue-600 to-indigo-600 text-white font-black text-xl rounded-2xl flex items-center justify-center gap-3 shadow-xl shadow-blue-500/25 mb-4 hover:scale-[1.02] transition-transform disabled:opacity-70">{submitting?<Loader2 size={24} className="animate-spin"/>:<><Award size={22}/>Show My GPS Match</>}</button><button onClick={()=>setStage("results")} className="w-full text-center text-base text-zinc-500 hover:text-zinc-300 font-medium py-2">Skip — just show me the results</button><p className="text-center text-sm text-zinc-600 mt-4">🔒 No spam. Unsubscribe anytime.</p></div></motion.div>)}
              {stage==="results"&&top&&(<motion.div key="results" initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="space-y-6">
                {submitted&&<div className="bg-green-900/30 border border-green-700 rounded-2xl p-5 flex items-center gap-3"><CheckCircle2 size={20} className="text-green-400 shrink-0"/><p className="text-base font-bold text-green-300">Report sent to {email} — check your inbox!</p></div>}
                <div className="bg-zinc-900 rounded-[2rem] border-2 border-blue-800 overflow-hidden shadow-xl"><div className="h-1.5 bg-gradient-to-r from-blue-500 to-indigo-400"/><div className="p-8"><div className="flex items-center gap-3 mb-6"><div className="w-10 h-10 bg-gradient-to-br from-amber-400 to-orange-500 rounded-full flex items-center justify-center"><Star size={18} className="text-white fill-white"/></div><span className="font-black text-amber-400 text-base uppercase tracking-widest">Your #1 Recommended GPS{name?` for ${name}`:""}</span></div><div className="flex items-start justify-between gap-4 mb-6"><div><h3 className="text-3xl font-black text-white mb-2">{top.name}</h3><div className="flex items-center gap-3"><span className={`${top.badgeColor} text-white text-sm font-black px-3 py-1.5 rounded-full`}>{top.badge}</span><span className="text-zinc-400 font-bold">{top.price}</span></div></div><div className="text-5xl">{top.emoji}</div></div><div className="grid grid-cols-2 gap-4 mb-6"><div className="bg-zinc-800 rounded-2xl p-5"><div className="text-xs font-black text-zinc-400 uppercase tracking-widest mb-2">Screen Size</div><div className="font-black text-white text-lg">{top.screen}</div></div><div className="bg-zinc-800 rounded-2xl p-5"><div className="text-xs font-black text-zinc-400 uppercase tracking-widest mb-2">Best For</div><div className="font-black text-white text-base">{top.bestFor[0]}</div></div></div><div className="mb-6"><div className="text-base font-black text-zinc-200 mb-3">Key Features:</div><div className="space-y-2">{top.features.map(f=>(<div key={f} className="flex items-center gap-3 text-base text-zinc-300 font-medium"><CheckCircle2 size={16} className="text-blue-400 shrink-0"/>{f}</div>))}</div></div><div className="grid grid-cols-2 gap-5"><div><div className="text-sm font-black text-green-400 uppercase tracking-widest mb-2">✓ Pros</div>{top.pros.map(p=><div key={p} className="text-sm text-zinc-400 font-medium mb-1.5">• {p}</div>)}</div><div><div className="text-sm font-black text-red-400 uppercase tracking-widest mb-2">✗ Consider</div>{top.cons.map(c=><div key={c} className="text-sm text-zinc-400 font-medium mb-1.5">• {c}</div>)}</div></div></div></div>
                <div className="bg-zinc-900 rounded-[2rem] border border-zinc-800 p-8"><h3 className="font-black text-white mb-5 text-xl">Also Consider</h3><div className="space-y-4">{ranked.slice(1,3).map((d,i)=>(<motion.div key={d.id} initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*0.1}} className="flex items-center gap-5 p-5 bg-zinc-800 rounded-2xl"><div className="text-3xl">{d.emoji}</div><div className="flex-1"><div className="font-black text-white text-base">{d.name}</div><div className="text-zinc-400 text-sm">{d.price} · {d.screen}</div></div><span className={`${d.badgeColor} text-white text-sm font-black px-3 py-1.5 rounded-full`}>{d.badge}</span></motion.div>))}</div></div>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><button onClick={reset} className="flex items-center justify-center gap-2 py-5 border-2 border-zinc-700 rounded-2xl font-black text-zinc-300 hover:border-zinc-500 text-lg"><RefreshCw size={20}/>Try Again</button><Link href="/tools/road-trip-checker"><div className="flex items-center justify-center gap-2 py-5 bg-gradient-to-r from-green-600 to-emerald-500 text-white font-black rounded-2xl shadow-lg cursor-pointer text-lg hover:scale-[1.02] transition-transform"><Navigation size={20}/>Road Trip Checklist</div></Link></div>
                <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5"><div className="flex items-start gap-3"><Shield size={14} className="text-zinc-500 mt-0.5 shrink-0"/><p className="text-sm text-zinc-500 font-medium">Educational guidance only. Not affiliated with Garmin, TomTom, or any GPS manufacturer.</p></div></div>
              </motion.div>)}
            </AnimatePresence>
          </div>
          <div className="space-y-6">
            <div className="bg-zinc-900 rounded-[2rem] border border-zinc-800 p-7"><h3 className="font-black text-white mb-5 text-base uppercase tracking-widest">⭐ GPS Buying Tips</h3><div className="space-y-4">{["Bigger screen = easier to read while driving","Lifetime maps save money long-term","Live traffic is worth it for city drivers","Bluetooth lets you call hands-free","Try the menu in-store before buying"].map((tip,i)=>(<div key={i} className="flex items-start gap-3 text-base text-zinc-400 font-medium"><CheckCircle2 size={16} className="text-green-400 shrink-0 mt-0.5"/>{tip}</div>))}</div></div>
            <Link href="/tools/road-trip-checker"><div className="bg-gradient-to-br from-green-600 to-emerald-600 rounded-[2rem] p-7 cursor-pointer hover:scale-[1.02] transition-transform"><div className="text-4xl mb-4">🚗</div><h3 className="font-black text-white mb-2 text-lg">Planning a road trip?</h3><p className="text-green-200 text-base font-medium mb-4">Check if your GPS is ready with our free 5-step pre-trip checklist.</p><div className="flex items-center gap-2 text-white font-black text-base">GPS Road Trip Check →</div></div></Link>
            <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-5"><div className="flex items-start gap-3"><Shield size={14} className="text-zinc-500 mt-0.5 shrink-0"/><p className="text-sm text-zinc-500 font-medium">Independent educational platform. Not affiliated with Garmin, TomTom, or any manufacturer.</p></div></div>
          </div>
        </div>
      </section>
      <section className="border-t border-zinc-800 py-20"><div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-4xl font-black text-white mb-8 tracking-tight">Choosing the Best GPS for Seniors & Adults 45+</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-zinc-400 font-medium leading-relaxed text-base"><p>The most important thing when choosing a GPS as an adult over 45 is screen size and menu simplicity. A larger screen — 5.5 inches or more — is dramatically easier to read at a glance while driving without straining your eyes.</p><p>All recommendations are for educational purposes only. Setwise Digital is an independent technology education platform not affiliated with Garmin, TomTom, or any GPS manufacturer.</p></div></div></section>
      <Footer/>
    </div>
  );
}
